image: "0xacab.org:4567/leap/gitlab-buildpackage:android"
#image: "gfx2015/android"

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
