#image: "0xacab.org:4567/leap/gitlab-buildpackage:android"
image: "jacekmarchwicki/android"

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
