image: "0xacab.org:4567/leap/gitlab-buildpackage:android"
#image: "gfx2015/android"

stages:
  - build

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
